version: "3.9"

services:
  # Application

  # Databases
  metadata-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metadata
    ports:
      - 5432:5432
    volumes:
      - metadata-db-volume:/var/lib/postgresql/data
      - $PWD/infra/metadata.sql:/docker-entrypoint-initdb.d/init.sql

  search-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: search
    ports:
      - 5433:5432
    volumes:
      - search-db-volume:/var/lib/postgresql/data
      - $PWD/infra/search.sql:/docker-entrypoint-initdb.d/init.sql

  auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - 5434:5432
    volumes:
      - auth-db-volume:/var/lib/postgresql/data
      - $PWD/infra/auth.sql:/docker-entrypoint-initdb.d/init.sql

  # Caches
      #
volumes:
  metadata-db-volume:
  search-db-volume:
  auth-db-volume:
