CREATE TABLE search (
  id BIGSERIAL PRIMARY KEY,
  word VARCHAR(100) NOT NULL,
  owner BIGINT NOT NULL,
  title VARCHAR(30) NOT NULL,
  description VARCHAR(100) NOT NULL,
  url VARCHAR NOT NULL,
  tag VARCHAR(100),
  upload_date TIMESTAMP DEFAULT NOW()
);
